# Generated by Django 3.0.8 on 2020-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='', max_length=12)),
                ('content', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
