# Generated by Django 3.0.8 on 2020-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20200821_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20)),
                ('content', models.TextField(default='', max_length=500)),
                ('author', models.IntegerField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
