# Generated by Django 3.0.8 on 2020-08-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
